### ISSUE TITLE
town hall model

### ISSUE THREAD

**Issue by kfarr** [3DStreet/citybuilderjr#4]
## model changes requested.

On this model:
https://sketchfab.com/3d-models/low-poly-cartoon-town-hall-d0022fe1b265486497b847049b2edfdf
(also attached as zip [cityhall.zip](https://github.com/3DStreet/citybuilderjr/files/13576618/cityhall.zip))

### Changes:
- [ ] - Trees from the scene will need to be moved closer to city hall to prevent them extending beyond the grass border.
- [ ] - Then the cityhall model should be downscaled to have a bounding box of -2, -2 to 2, 2 similar to but twice the size of a normal road tile. More scale information is below. 
- [ ] - text on building should say "CITYHALL" instead of "TOWNHALL"
- [ ] - the models green "ground" should be the same height as other road or grass tile models from kaykit (0.1 I think), and it should not have the brown color ground below.

### Scale information:

right now this townhall model has a bounding box values below [in catalog.json after building](https://github.com/3DStreet/citybuilderjr#build-instructions) 
```
    "bboxMin": [
      -8.2258,
      -6.62695,
      -7.63921
    ],
    "bboxMax": [
      10.54704,
      7.86515,
      10.8422
    ],
```

a normal tile like 'road_straight' has a bounding box of something like
```
    "bboxMin": [
      -1,
      0,
      -1
    ],
    "bboxMax": [
      1,
      0.1,
      1
    ],
```

instead, the cityhall model should be downscaled to have a bounding box of below. **Trees from the scene will need to be relocated closer to city hall to prevent them extending beyond the grass border.
```
    "bboxMin": [
      -2,
      0,
      -2
    ],
    "bboxMax": [
      2,
      ?,
      2
    ],
```

**Comment by kfarr** [comment]
https://sketchfab.com/3d-models/low-poly-cartoon-town-hall-d0022fe1b265486497b847049b2edfdf

**Comment by gnansai** [comment]
Hi @kfarr 
Here is the latest model of the Town Hall.
[TownHall_v01.zip](https://github.com/3DStreet/citybuilderjr/files/13628565/TownHall_v01.zip)

1. I have moved the trees closer.
![image](https://github.com/3DStreet/citybuilderjr/assets/25223402/5f8b8ae1-b22d-4304-b009-3a653b9a3973)
2. I have added CITY HALL text
![image](https://github.com/3DStreet/citybuilderjr/assets/25223402/84aa2b65-4997-4acb-a2e8-2e11cfe525a2)
3. I have removed the brown ground
4. I have kept the scale of 2,2 across X and Y axis in Blender.

**Comment by gnansai** [comment]
Could you share the grass tile model so that I could adjust the grass of Town Hall model?

**Comment by kfarr** [comment]
here are examples like "park base"
https://github.com/3DStreet/citybuilderjr/tree/main/src/models/kaykit

**Comment by gnansai** [comment]
Hi @kfarr 
I have made the grass in Town hall same as the "park base"
![Screenshot 2023-12-13 095947](https://github.com/3DStreet/citybuilderjr/assets/25223402/62775aa2-1cbf-4a79-9f90-b6d3e739b9bd)
Here is the latest version
[TownHall_v02.zip](https://github.com/3DStreet/citybuilderjr/files/13656008/TownHall_v02.zip)

**Comment by gnansai** [comment]
Hi @kfarr 
The town hall is using multiple materials for each color. Shall I convert it to one material using single image texture(https://github.com/3DStreet/citybuilderjr/blob/main/src/models/kaykit/citybits_texture.png) ?
![image](https://github.com/3DStreet/citybuilderjr/assets/25223402/17c9a7dd-53eb-40c2-894c-a419a0cc0a38)

**Comment by kfarr** [comment]
@gnansai yeah ideally it's the same as kaykit a single image texture palette atlas

**Comment by gnansai** [comment]
Hi @kfarr 
I have adjusted the UVs of the Town Hall to use single texture. I have exported as GLTF model and added Draco compression as the other models in Kaykit.
![image](https://github.com/3DStreet/citybuilderjr/assets/25223402/8049e6c2-be71-41cd-980d-345964a52be4)

[TownHall_v03_citybits_texture_atlas.zip](https://github.com/3DStreet/citybuilderjr/files/13656912/TownHall_v03_citybits_texture_atlas.zip)

**Comment by kfarr** [comment]
It looks excellent!

![image](https://github.com/3DStreet/citybuilderjr/assets/470477/8f1f89f6-8a62-4218-8476-300482ead1e1)
